CREATE TABLE users (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_id CHAR(26) NOT NULL UNIQUE,
  display_name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NULL UNIQUE,
  role ENUM('PLAYER','CITY_CAPTAIN','ORGANISATION_MANAGER','MODERATOR','ADMIN') NOT NULL DEFAULT 'PLAYER',
  status ENUM('ACTIVE','SUSPENDED','DELETED') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE cities (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  country VARCHAR(120) NOT NULL,
  code VARCHAR(12) NOT NULL UNIQUE,
  tier ENUM('PREMIER','CHAMPIONSHIP','RISING') NOT NULL DEFAULT 'PREMIER',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE seasons (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  status ENUM('DRAFT','QUALIFICATION','GROUP','KNOCKOUT','FINAL','COMPLETE','ARCHIVED') NOT NULL DEFAULT 'DRAFT',
  starts_at DATETIME NULL,
  ends_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE season_cities (
  season_id BIGINT UNSIGNED NOT NULL,
  city_id BIGINT UNSIGNED NOT NULL,
  status ENUM('QUALIFYING','QUALIFIED','ELIMINATED','CHAMPION') NOT NULL DEFAULT 'QUALIFYING',
  qualification_total INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY(season_id,city_id),
  CONSTRAINT fk_sc_season FOREIGN KEY(season_id) REFERENCES seasons(id),
  CONSTRAINT fk_sc_city FOREIGN KEY(city_id) REFERENCES cities(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE city_memberships (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  season_id BIGINT UNSIGNED NOT NULL,
  city_id BIGINT UNSIGNED NOT NULL,
  status ENUM('ACTIVE','LEFT','SUSPENDED') NOT NULL DEFAULT 'ACTIVE',
  joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_membership(user_id,season_id),
  CONSTRAINT fk_cm_user FOREIGN KEY(user_id) REFERENCES users(id),
  CONSTRAINT fk_cm_season FOREIGN KEY(season_id) REFERENCES seasons(id),
  CONSTRAINT fk_cm_city FOREIGN KEY(city_id) REFERENCES cities(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE matches (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  season_id BIGINT UNSIGNED NOT NULL,
  round_code VARCHAR(40) NOT NULL,
  home_city_id BIGINT UNSIGNED NOT NULL,
  away_city_id BIGINT UNSIGNED NOT NULL,
  starts_at DATETIME NOT NULL,
  ends_at DATETIME NULL,
  status ENUM('SCHEDULED','LOBBY','LIVE','FINAL','CANCELLED') NOT NULL DEFAULT 'SCHEDULED',
  home_score INT UNSIGNED NOT NULL DEFAULT 0,
  away_score INT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_match_season FOREIGN KEY(season_id) REFERENCES seasons(id),
  CONSTRAINT fk_match_home FOREIGN KEY(home_city_id) REFERENCES cities(id),
  CONSTRAINT fk_match_away FOREIGN KEY(away_city_id) REFERENCES cities(id),
  INDEX ix_match_season_status(season_id,status),
  INDEX ix_match_starts(starts_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE match_participations (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  match_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  city_id BIGINT UNSIGNED NOT NULL,
  parent_participation_id BIGINT UNSIGNED NULL,
  share_token CHAR(32) NOT NULL UNIQUE,
  generation SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  direct_joins INT UNSIGNED NOT NULL DEFAULT 0,
  downstream_joins INT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_match_user(match_id,user_id),
  CONSTRAINT fk_mp_match FOREIGN KEY(match_id) REFERENCES matches(id),
  CONSTRAINT fk_mp_user FOREIGN KEY(user_id) REFERENCES users(id),
  CONSTRAINU fk_mp_city FOREIGN KEY(city_id) REFERENCES cities(id),
  CONSTRAINT fk_mp_parent FOREIGN KEY(parent_participation_id) REFERENCES match_participations(id),
  INDEX ix_mp_parent(parent_participation_id),
  INDEX ix_mp_city_match(match_id,city_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE scoring_events (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  match_id BIGINT UNSIGNED NOT NULL,
  city_id BIGINT UNSIGNED NOT NULL,
  participation_id BIGINT UNSIGNED NULL,
  type ENUM('GOAL','ASSIST','ADJUSTMENT','REVERSAL') NOT NULL,
  points SMALLINT NOT NULL,
  reason VARCHAR(255) NULL,
  idempotency_key VARCHAR(100) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_se_match FOREIGN KEY(match_id) REFERENCES matches(id),
  CONSTRAINT fk_se_city FOREIGN KEY(city_id) REFERENCES cities(id),
  CONSTRAINT fk_se_participation FOREIGN KEY(participation_id) REFERENCES match_participations(id),
  INDEX ix_se_match_city(match_id,city_id,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE awards (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  match_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  type ENUM('MAN_OF_MATCH','TOP_PLAYMAKER','GLOBAL_CONNECTOR','FINAL_ASSIST') NOT NULL,
  metric_value INT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_award(match_id,type),
  CONSTRAINT fk_aw_match FOREIGN KEY(match_id) REFERENCES matches(id),
  CONSTRAINT fk_aw_user FOREIGN KEY(user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE moderation_cases (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  entity_type ENUM('USER','CITY','MATCH','PARTICIPATION') NOT NULL,
  entity_id BIGINT UNSIGNED NOT NULL,
  status ENUM('OPEN','REVIEWING','RESOLVED','DISMISSED') NOT NULL DEFAULT 'OPEN',
  reason VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resolved_at DATETIME NULL,
  INDEX ix_mod_status(status,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE audit_log (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  actor_user_id BIGINT UNSIGNED NULL,
  action VARCHAR(100) NOT NULL,
  entity_type VARCHAR(60) NOT NULL,
  entity_id VARCHAR(80) NOT NULL,
  metadata_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX ix_audit_entity(entity_type,entity_id,created_at),
  CONSTRAINT fk_audit_actor FOREIGN KEY(actor_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
